excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://GrimaG.github.io
name: P| o.O| 2
description: This blog contains all the content on updates made on GitHub regarding POO2 of discipline ture 2015-1
author: Gustavo Grimaldi
avatar: https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xap1/v/t1.0-9/1538807_10202568939615668_330351241_n.jpg?oh=daefa7ed2ddeff7c8e276bfb61993900&oe=55E04CD8&__gda__=1436363392_a2be92d2d48bc740ced7523d03f0c21b
ga_domain: 
ga_tracking_id: 